name: dash_kit_lints
description: The custom set of lint rules based on the package:flutter_lints
version: 1.0.7
repository: https://github.com/Dash-Kit/dash-kit-lints

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.2
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
